version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    environment:
      VITE_BACKEND_URL: http://api:5000
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    build: ./server
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: mongodb://db:27017/task
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - task:/data/db

volumes:
  task:
