services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./client/.env

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./server/.env
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      target: development
