services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_BACKEND_URL=${API_URL:-http://localhost}
    env_file:
      - ./client/.env.prod

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      target: production
